### ISSUE TITLE
Link to xref

### ISSUE THREAD

**Issue by jambulud** [devonfw/docgen#18]
Hi,

I have been checking docgen and I found the following line:
https://github.com/devonfw/docgen/blob/master/pom.xml#L171

here  `link` is replaced with `xref` and `.asciidoc` is also being added to xref. However in asciidoctor's documentation they do not use an extension when adding xrefs

![image](https://user-images.githubusercontent.com/43032659/73640307-4a975500-466e-11ea-916e-8813877883b9.png)

url of the image: https://asciidoctor.org/docs/user-manual/#internal-cross-references

**Comment by jambulud** [comment]
I'm writting this as a "enhancemenet" because I didn't found any template for "questions"

**Comment by hohwille** [comment]
@jambulud thanks for pointing this out. It might be related to the bug we are facing with our broken links.
However, for clarification this corresponds to this line:
https://github.com/devonfw/docgen/blob/master/pom.xml#L193

IMHO this is perfectly correct as the filename will always carry the `.asciidoc` extension suffix. The question is wheter converting `xlink` to `xref` is correct for the website at all as in the website not everything is in one file but sometimes `xlink`s are real hyperlinks to another file and in other cases several `.asciidoc` files are merged into the same HTML document and therefore `xlink` needs to be converted to `xref`.

How could `docgen` know when to do what in such case?

**Comment by hohwille** [comment]
@jambulud for your understanding it might help to diff the original asciidoc files with the ones generated by docgen in `target/asciidoc`. There you will quickly get what is happening and why...

**Comment by jambulud** [comment]
Is there a way to avoid adding ".asciidoc" in the IDs?
![image](https://user-images.githubusercontent.com/43032659/73650517-a79d0600-4682-11ea-8d17-0fb09ebd283a.png)

The "html splitter" (https://github.com/owenh000/asciidoctor-multipage/) takes those IDs and generate html files using it as part of the name, obtaining:

![image](https://user-images.githubusercontent.com/43032659/73650743-24c87b00-4683-11ea-9c1a-8159a0b183a0.png)

Why is this important? because due to this we get urls like `https://devonfw.com/website/pages/docs/architecture.asciidoc.html` (notice the '.asciidoc')

Also, it makes difficult to link to these files using [asciidoc inter-document cross references](https://devonfw.com/website/pages/docs/architecture.asciidoc.html) because 

If you write <<document-x.asciidoc#, Link to doc X>>, it will be `http:.../document-x.html` after the transformation. As mentioned before, the document in our website would NOT be `document-x.html` but  `document-x.asciidoc.html`
To get the correct link to `document-x.asciidoc.html` we have to write <<document-x.asciidoc.asciidoc#, Link to doc X>> (double asciidoc)

**Comment by jambulud** [comment]
> How could `docgen` know when to do what in such case?

This may help: https://asciidoctor.org/docs/user-manual/#inter-document-cross-references
It seems that the syntax `<<document-b.adoc#section-b,Section B>>` changes the created link depending on whether the file is included or not

**Comment by hohwille** [comment]
Hi @jambulud we could remove the `.asciidoc` suffix from both the document anchor links as well as from anchor references (`link:*#anchor` and `xref:anchor`). However, this will either break `docgen` when other extensions (e.g. `.adoc`) is used or requires additional normization logic. Anyhow, if this helps we can surely consider this as a feature-request for docgen and get this fixed via a PR.

**Comment by hohwille** [comment]
> If you write <<document-x.asciidoc#, Link to doc X>>, it will be http:.../document-x.html after the transformation. As mentioned before, the document in our website would NOT be document-x.html but document-x.asciidoc.html
To get the correct link to document-x.asciidoc.html we have to write <<document-x.asciidoc.asciidoc#, Link to doc X>> (double asciidoc)

First of all we should not use the `<<url, anchor>>` syntax but `link:url#anchor` instead as described in docgen best practices.  However, if you are correct that means that `asciidoc-multipage` is replacing the original extension `.asciidoc` with `.html` in `link` tags while it takes the document anchor ID as the filename. This sounds really odd and wrong. Furhter it confuses me as in other links that also contain `.asciidoc` suffix it works and the HTML hyperlink ends up as `.asciidoc.html` on the website. So how do you explain this?
Anyhow, if we are 100% sure that you are correct and this would fix the bug we should surely change docgen accordingly. However, I am not yet convinced this is the case. We might build a feature that might fix some links and break others. However, we could test this locally when building the website by patching the docgen localy via some SNAPSHOT.

**Comment by jambulud** [comment]
> Furhter it confuses me as in other links that also contain `.asciidoc` suffix it works and the HTML hyperlink ends up as `.asciidoc.html` on the website. So how do you explain this?

Do you have any example of that?  So I can check those mentioned cases

**Comment by jambulud** [comment]
# Links during the phases of the website generation

The examples shown below are written inside devon4j/architecture.asciidoc

## Initial state:
coding conventions.asciidoc is referenced with (yellow) and without (red) the anchor `package`

![image](https://user-images.githubusercontent.com/43032659/74511129-8e5b4b80-4f05-11ea-810d-50874962be86.png)

## docgen preprocessing:
Yellow: 
* If the `link:` added has the extension included, docgen adds the anchor as part of the `xref:` ( _anchor )
* If the `link:` added does not have the extension included, it maintains the anchor in `xref:` (#anchor)

Red:
* If the `link:` added has the extension included, docgen just changes it to an `xref:`
* If the `link:` added does not have the extension included, docgen adds the extension and then converts it to `xref:` 

![image](https://user-images.githubusercontent.com/43032659/74511139-9a470d80-4f05-11ea-9fdb-aab538831512.png)


## html splitting process
Yellow: 
* If the `link:` added (initial state) had the extension included and an anchor, the html splitter transform it into 
liked-file.asciidoc.html#linked-file.asciidoc_anchor (coding-conventions.asciidoc.html#coding-conventions.asciidoc_packages)
* If the `link:` added (initial state) does not have extension but has anchor, afther the transformation it will just have the extension added. The anchor is maintained.

Red:
* the file is correctly referenced (.asciidoc.html) but has no anchor

![image](https://user-images.githubusercontent.com/43032659/74511158-a4690c00-4f05-11ea-9f7c-fd2d19eb51f0.png)

**Comment by hohwille** [comment]
I agree that 
```
link:coding-conventions#packages[coding conventions]
```
and
```
link:coding-conventions.asciidoc#packages[coding conventions]
```

Should be interchangeable. The idea of docgen is the have replacement logic that would transfer the first into the second automatically.
Therefore both should end up to the same result.
We should add automated test-cases for docgen testing things like this.
IMHO it is already fixed but I also might be wrong. Only a test can prove it.

**Comment by maybeec** [comment]
Fully agree, would be even better if we start to have proper test coverage to make maintenance easier in future

**Comment by hohwille** [comment]
> We should add automated test-cases for docgen testing things like this.
IMHO it is already fixed but I also might be wrong. Only a test can prove it.

Either we are facing new issues on our website with broken links or this issue is still not fixed.
We urgently have to raise the priority of this issue.
We have broken links on our website for many years now and that is simply unprefessional and poor.

**Comment by hohwille** [comment]
https://devonfw.com/website/pages/docs/guide-dependency-injection.asciidoc.html
is (from bullet `stateless`) linking to 
https://devonfw.com/website/pages/docs/coding-conventions.html#stateless-programming
The correct link would actually bee:
https://devonfw.com/website/pages/docs/coding-conventions.asciidoc.html#coding-conventions.asciidoc_stateless-programming

So I see two errors here:
1. the target filename is `«file».asciidoc.html`. So either this is wrong and the files should be generated as `«file».html` hiding the source technology or the links in the HTML have to contain the proper `.asciidoc.html` extension.
2. the anchor is wrong. IMHO the prefix `coding-conventions.asciidoc_` comes from docgen to make the anchors/section-IDs unique for the entire documentation. In that case it seems like a bug in docgen that here the anchor remains as `stateless-programming` where it should be rewritten to `coding-conventions.asciidoc_stateless-programming`.

**Comment by hohwille** [comment]
What seems interesting to me is that in
https://devonfw.com/website/pages/docs/coding-conventions.asciidoc.html#coding-conventions.asciidoc_packages
under `«layer»` we have two broken links pointing to the classic and modern structure.
However here the same links seem to work:
https://devonfw.com/website/pages/docs/guide-structure.asciidoc.html

**Comment by hohwille** [comment]
I found even more and different errors:
https://devonfw.com/website/pages/docs/guide-database-migration.asciidoc.html
The `database` link is broken as it leads to:
https://github.com/devonfw/devonfw-guide/blob/master/general/db/guide-database
However, the correct link would be:
https://github.com/devonfw/devonfw-guide/blob/master/general/db/guide-database.asciidoc
So the `.asciidoc` extension is missing or has been cut off.
It is present in the source asciidoc file:
https://github.com/devonfw/devon4j/blob/master/documentation/guide-database-migration.asciidoc

Besides the "Pencil" icon on the website from the link above is also broken and leading to a totally wrong URL.

**Comment by maybeec** [comment]
might be also fixed by #31

**Comment by maybeec** [comment]
as of the latest changes unfortunately most of the links do not work anymore, as we needed to unify the URLs by encoding the folder structure in it to properly transfer links to xref. Now it seems to be fixed.
For sure, we can discuss removing .asciidoc extension. I am not yet sure, why instead it's added all the time in the regular expressions. Possibly we should give it a try to remove all endings (adoc / assciidoc / ...) any comments on that why it was done the other way around? @hohwille

**Comment by hohwille** [comment]
If still relevant, please file a new issue for the extension thing. I agree that docgen should work both with `.adoc` and with `.asciidoc`.
However, this issue itself is fixed and I therefore close it. I am fighting against this tendency in devonfw to have issues that can never get closed...
